### ISSUE TITLE
EXCEPTION FROM SIMULATION: expected type int[] but found float[]

### ISSUE THREAD

**Issue by minsko** [pxb1988/dex2jar#133]
This issue is encountered when converting the jar back to dex from the simple android project example at: <https://github.com/minsko/iTextPdfTest>

This was originally tested with the 2.0 release, but also happens with a current build of the 2.x branch.

With the 2.0 release, the error is:

```
EXCEPTION FROM SIMULATION:
expected type int[] but found float[]

...at bytecode offset 00000117
locals[0000]: Lcom/itextpdf/text/pdf/PdfDeviceNColor;
locals[0001]: Lcom/itextpdf/text/pdf/PdfWriter;
locals[0002]: <invalid>
locals[0003]: <invalid>
locals[0004]: <invalid>
locals[0005]: <invalid>
locals[0006]: <invalid>
locals[0007]: <invalid>
locals[0008]: I
locals[0009]: <invalid>
locals[000a]: I
locals[000b]: string{""}
locals[000c]: Lcom/itextpdf/text/pdf/PdfArray;
locals[000d]: Lcom/itextpdf/text/pdf/PdfArray;
locals[000e]: Lcom/itextpdf/text/pdf/PdfDictionary;
locals[000f]: [F
locals[0010]: [[F
locals[0011]: Lcom/itextpdf/text/BaseColor;
...while working on block 0114
...while working on method getPdfObject:(Lcom/itextpdf/text/pdf/PdfWriter;)Lcom/itextpdf/text/pdf/PdfObject;
...while processing getPdfObject (Lcom/itextpdf/text/pdf/PdfWriter;)Lcom/itextpdf/text/pdf/PdfObject;
...while processing com/itextpdf/text/pdf/PdfDeviceNColor.class

1 error; aborting
```

With a 2.x branch build, the error is simply:

```
Uncaught translation error: com.android.dx.cf.code.SimException: expected type int[] but found float[]
1 error; aborting
```

**Comment by xlyashuk** [comment]
Hi @minsko ,
Have you tried to build dex2jar from latest sources? I have build an apk from your project and was able to convert dex file to jar and back.

**Comment by Lanchon** [comment]
get builds here:
https://github.com/Lanchon/dex2jar/releases

**Comment by xlyashuk** [comment]
Your builds worked for me too. Can you attach problematic APK or classes.dex?
I have attached my classes.dex built for your project.
[classes.zip](https://github.com/pxb1988/dex2jar/files/1253883/classes.zip)

**Comment by minsko** [comment]
Thanks, I had built and tried the latest 2.x branch previously.  I just pulled and built again, the issue has been resolved.
