### ISSUE TITLE
Detail Error Information in File ./classes-error.zip

### ISSUE THREAD

**Issue by avikmrr** [pxb1988/dex2jar#141]

**Comment by peixinchen** [comment]
How did you solute the problem? I have a same one as it. Thx

**Comment by sivapraka** [comment]
I have the same problem

**Comment by baioug** [comment]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/2781236/classes-error.zip)

**Comment by linnahan** [comment]
I have the same problem

**Comment by zhaihoy** [comment]
I have the same problem ？How did you solute the problem？
