### ISSUE TITLE
Bug: default method found in version 50.0 classfile

### ISSUE THREAD

**Issue by Lanchon** [pxb1988/dex2jar#143]
head (1d515072d5a49a8f82a761a8081e36b1923af541) produces invalid java bytecode when translating dex files with java 7 features (eg: default methods) or Java 8 features (eg: *invoke-polymorphic* or *invoke-custom*).

**Comment by Lanchon** [comment]
fixed here: https://github.com/Lanchon/dex2jar/commit/981efdd9d6ca5aac6d4c8a8fd16106979e6c68f6

**Comment by Lanchon** [comment]
a fix for this was attempted in official dex2jar on Jun 6, 2018 with https://github.com/pxb1988/dex2jar/commit/85b1b3b8ddabd285b02921fce0713660e8eb0cfe.

however, bug https://github.com/pxb1988/dex2jar/issues/194 was introduced by the attempt.

**Comment by pxb1988** [comment]
Duplicate of #194

**Comment by Lanchon** [comment]
not really a duplicate of #194.

but should be fixed with 85b1b3b8ddabd285b02921fce0713660e8eb0cfe and b5771406a9c3073ba25fdfe4e43146ca36f655dc.

thanks!
