### ISSUE TITLE
package not complete

### ISSUE THREAD

**Issue by minggangLu** [pxb1988/dex2jar#151]
when i use the newest dex2jar （2.1 snapshot），the classes's packages is  not complete ,when i use AS's analyze apk,the   struct is 
![complete](https://user-images.githubusercontent.com/32918793/33600530-741f56f0-d9e4-11e7-9d85-c6abf54c4f17.png)
when use the jd-gui  see the classes,the struct is 
![image](https://user-images.githubusercontent.com/32918793/33600549-8b41d4d4-d9e4-11e7-81c0-51792cabb9aa.png)
only have three packages,every dex has only three packages

**Comment by minggangLu** [comment]
not the tool's proble!!,is the muti dex

**Comment by Lanchon** [comment]
dex2jar supports multidex, look for my d2j fork for updated builds.
