### ISSUE TITLE
Provide binaries as well

### ISSUE THREAD

**Issue by Nolaan** [pxb1988/dex2jar#17]
Hello,
it would be nice and time saving for your users to also provide the binaries with the release feature of github.
Thanks

**Comment by pxb1988** [comment]
thanks @Nolaan, i finally find the release feature.

Published
[Nightly build for dex2jar 20150601](https://github.com/pxb1988/dex2jar/releases/tag/2.1-nightly-26)
[dex2jar 2.0](https://github.com/pxb1988/dex2jar/releases/tag/2.0)

**Comment by Nolaan** [comment]
Waw!!!:D Man you're awesome!!!
Thanks for me and all the others who will download it ;) !
