### ISSUE TITLE
Errors translating classes.dex into jar for simple Android app

### ISSUE THREAD

**Issue by mithadis** [pxb1988/dex2jar#175]
Reporting the error as requested by the tool in error message. Using dex2jar version 2.0 on Windows, script d2j-dex2jar.bat.

[input-output.zip](https://github.com/pxb1988/dex2jar/files/1954788/input-output.zip)

[classes-error.zip](https://github.com/pxb1988/dex2jar/files/1954769/classes-error.zip)

**Comment by limkokhole** [comment]
I look at the summary.txt in your zip, it shows version 2.0, you should know that the lastet version is 2.1 which you can clone from git, but not download from sourceforge which is still 2.0.

You can watch [my youtube video](https://www.youtube.com/watch?v=j9nTB0x0PvU) if still has trouble.

**Comment by mithadis** [comment]
No error messages when using new version (2.1 instead of 2.0).
