### ISSUE TITLE
IllegalArgumentException / java.nio.Buffer.position(Buffer.java:244)

### ISSUE THREAD

**Issue by LucasEsposito** [pxb1988/dex2jar#185]
Running the following command:
> sh /dex2jar/d2j-dex2jar.sh apk_path 63c75faf1493c6bf6a6c77e630660e160c8e4239.codex jar_path /tmpfs/jar.jar

I got the following error:
> java.lang.IllegalArgumentException
> 	at java.nio.Buffer.position(Buffer.java:244)
> 	at com.googlecode.d2j.util.zip.ZipFile.skip(ZipFile.java:167)
> 	at com.googlecode.d2j.util.zip.ZipFile.readCentralDir(ZipFile.java:247)
> 	at com.googlecode.d2j.util.zip.ZipFile.<init>(ZipFile.java:74)
> 	at com.googlecode.d2j.util.zip.ZipFile.<init>(ZipFile.java:78)
> 	at com.googlecode.d2j.reader.zip.ZipUtil.readDex(ZipUtil.java:79)
> 	at com.googlecode.d2j.reader.zip.ZipUtil.readDex(ZipUtil.java:57)
> 	at com.googlecode.d2j.reader.zip.ZipUtil.readDex(ZipUtil.java:53)
> 	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
> 	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
> 	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)

The apk is a **malware**. It's hash is 63c75faf1493c6bf6a6c77e630660e160c8e4239: https://www.virustotal.com/es-ar/file/54a9091cf54d76d05927788e541be5edc98642580b008681a2bd51c1ad4371a8/analysis/

You can download the file from here: https://ufile.io/tyz9o
or also from here: https://files.fm/down.php?i=pycxvdc7

The file will be online for 2 months. Let me know if you want to download the sample and it's removed, so I can upload it again :)

**Comment by pxb1988** [comment]
the file is extractable by `unzip`, but `7z`  complains

````
ERRORS:
Unexpected end of archive
````

**Comment by LucasEsposito** [comment]
Thanks! 👍
