### ISSUE TITLE
dex2jar error processing file (report attached)

### ISSUE THREAD

**Issue by LucasEsposito** [pxb1988/dex2jar#186]
I got an error using dex2jar on the file with hash: 888438664647d2600dcf19f663dfb2ca244cbcc0.
I attached the zip generated by dex2jar:
[apk-error.zip](https://github.com/pxb1988/dex2jar/files/2069847/apk-error.zip)

```
root@5cbd34cb9c23:/myapp/src/tests/plugins/apk# rm -rf /tmpfs/*
root@5cbd34cb9c23:/myapp/src/tests/plugins/apk# sh /dex2jar/d2j-dex2jar.sh ./888438664647d2600dcf19f663dfb2ca244cbcc0.codex -o /tmpfs/output.jar
dex2jar ./888438664647d2600dcf19f663dfb2ca244cbcc0.codex -> /tmpfs/output.jar
Detail Error Information in File ./888438664647d2600dcf19f663dfb2ca244cbcc0-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.
root@5cbd34cb9c23:/myapp/src/tests/plugins/apk# file --mime-type ./888438664647d2600dcf19f663dfb2ca244cbcc0.codex 
./888438664647d2600dcf19f663dfb2ca244cbcc0.codex: application/java-archive
```

I'm not sure whether the file is a **malware** or not.
Here are two links for download:
https://ufile.io/hinr3
https://files.fm/f/7vfbkxqz

Please let me know if the file get removed and I'll be pleased to upload it again. Use the password **codex** to decompress the zip file to get the APK (file with *.codex extension).

Thanks!

**Comment by LucasEsposito** [comment]
Thanks! 👍

**Comment by EdawKing** [comment]
file has been remove
