### ISSUE TITLE
SDK 29 not supported

### ISSUE THREAD

**Issue by IacobIonut01** [pxb1988/dex2jar#189]
com.googlecode.d2j.DexException: not support version.                                                                                at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:151)                                                  at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:211)                                                  at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)                                           at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)                                                          
at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)

**Comment by lxzh** [comment]
Why close this issue? Solved?

**Comment by zhuhj8** [comment]
i  have the same isses
