### ISSUE TITLE
[BUG] incorrect handling of dex version 037

### ISSUE THREAD

**Issue by Lanchon** [pxb1988/dex2jar#194]
you added this line: https://github.com/pxb1988/dex2jar/commit/85b1b3b8ddabd285b02921fce0713660e8eb0cfe#diff-5022c0a5241d26f08995621848c1d097R403.

however, DEX 037 adds default interface methods:
> Note: Support for version 037 of the format was added in the Android 7.0 release. Prior to version 037 most versions of Android have used version 035 of the format. The only difference between versions 035 and 037 is the addition of default methods and the adjustment of the invoke.
https://source.android.com/devices/tech/dalvik/dex-format

and default methods were added in Java 8, not Java 7:
> Default methods enable new functionality to be added to the interfaces of libraries and ensure binary compatibility with code written for older versions of those interfaces.
http://www.oracle.com/technetwork/java/javase/8-whats-new-2157071.html

so you should use Opcodes.V1_8 when processing dex 037.

btw, i've got a different implementation of this dex version to java version mapping here:
https://github.com/DexPatcher/dex2jar/commit/981efdd9d6ca5aac6d4c8a8fd16106979e6c68f6#diff-5022c0a5241d26f08995621848c1d097R331

**Comment by pxb1988** [comment]
it's interesting, here is a map of java version and the dex version
 
JAVA | DEX | note
------------ | ------------- | -------------
6 | 035 | the start
7 | x | add invoke-dynamic
8 | x | add default method
x | 037 | add default method
x | 038 | add  invoke-dynamic A.K.A. polymorphic/custom

the order of java7 and 8 features are reversed in DEX. yes, changing DEX_037 to java8 is the solution.

**Comment by Lanchon** [comment]
your code fix is ok.

and your message was not, but you fixed it before i replied :-) :+1: :+1: 

to answer your earlier message:
> as DEX_037 support both invoke-dynamic and default method, translate it to java8 should work.
but i think it is not the best solution: for DEX_037 we should use java8 if we find default method, otherwise we use java7.

of course the versions are wrong in that text. but regarding the idea of detection: i suspect dx/d8 already detect usage and try to output 035 dex if features are not used.

i made this [android framework patcher](https://github.com/Lanchon/haystack) based on [a tool of mine](https://dexpatcher.github.io/) that is based on smali's dexlib2 that fails on any dex > 035. of course i expected the patcher not to work on Oreo, i didn't even test. but reports started coming in that the patcher worked fine on Android 8! which means Android 8 ships its framework as dex 035. why? no idea. maybe dx/d8 detects used features in code?

so you should not do this if dx is already doing it. also, it is best to provide a faithful translation: dex >= 037 -> java 8. use by reflection might require java 8 even if you don't see it in code. (android doesnt have this problem: code compatibility (reflection, etc) is declared in the manifest. dex version only needs to express features that the dex code actually uses. in java, bytecode version expresses bytecode operands AND the jre version.)
