### ISSUE TITLE
There are 1 methods fail to translate.

### ISSUE THREAD

**Issue by xakod** [pxb1988/dex2jar#208]
[summary.txt](https://github.com/pxb1988/dex2jar/files/2280144/summary.txt)

**Comment by xakod** [comment]
I really dont understand why smth went wrong, i have same errors on ubuntu

**Comment by Sidharth99** [comment]
found any solution @Jihadist ?

**Comment by xakod** [comment]
nope(

чт, 18 апр. 2019 г., 23:10 Sidharth jain <notifications@github.com>:
