### ISSUE TITLE
dex2jar occurs Error Information in File

### ISSUE THREAD

**Issue by yhongm** [pxb1988/dex2jar#210]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/2293150/classes-error.zip)
this is the error info file

**Comment by owen800q** [comment]
I have the same problem too
when i converted a apk file to jar, the error message shown 
Detail Error Information in File ./xxxx-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.

**Comment by Sidharth99** [comment]
@owen800q @yhongm did you find any solution for that?

**Comment by yhongm** [comment]
> @owen800q @yhongm did you find any solution for that?

no

**Comment by zjw950323** [comment]
Detail Error Information in File ./classes-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.

**Comment by hbasafa** [comment]
I think some apk files include different structure than the dex2jar specified structure; so they should add more features to this tool.

**Comment by sunitashirsatmore** [comment]
Why did you close the issue? Did you got the solution? I am also facing same issue.

**Comment by yhongm** [comment]
no
