### ISSUE TITLE
classes-error.zip

### ISSUE THREAD

**Issue by gooooooa** [pxb1988/dex2jar#301]
[boot_classes-error.zip](https://github.com/pxb1988/dex2jar/files/3519435/boot_classes-error.zip)

**Comment by gooooooa** [comment]
This is another one.
[boot-framework_classes2-error.zip](https://github.com/pxb1988/dex2jar/files/3519463/boot-framework_classes2-error.zip)

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
