### ISSUE TITLE
Isssue Related to DexJar tool Please reply it's Argent

### ISSUE THREAD

**Issue by rajrathod2001** [pxb1988/dex2jar#356]
Hello sir,
              When i run Dex2jr tool in cmd for conver classes.dex file to java file, it shows like this.

C:\Users\ABCD\Desktop\Adw0rm>d2j classes.dex
dex2jar classes.dex -> .\classes-dex2jar.jar
Detail Error Information in File .\classes-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.

What is a solution for this .I try for last 
 days.

**Comment by Noblerana** [comment]
Does it work with all programming languages

**Comment by pxb1988** [comment]
please file a new issue and attach the classes-error.zip
