### ISSUE TITLE
Problem with Ludo King

### ISSUE THREAD

**Issue by BugBoy13** [pxb1988/dex2jar#359]
[ludo.apk-error.zip](https://github.com/pxb1988/dex2jar/files/4512167/ludo.apk-error.zip)

**Comment by lihas** [comment]
I am trying to use dex2jar in WSL Ubuntu installed on my windows 10 from MS store.
While running dex2jar it showed me that an error has occurred, and that I should upload error info to this URL.

[LudoKing-error.zip](https://github.com/pxb1988/dex2jar/files/4578425/LudoKing-error.zip)
[LudoKing.apk.zip](https://github.com/pxb1988/dex2jar/files/4578431/LudoKing.apk.zip)
[dex2jar-2.0.zip](https://github.com/pxb1988/dex2jar/files/4578482/dex2jar-2.0.zip)


[apk.zip.004.zip](https://github.com/pxb1988/dex2jar/files/4578455/apk.zip.004.zip)
[apk.zip.005.zip](https://github.com/pxb1988/dex2jar/files/4578456/apk.zip.005.zip)
[apk.zip.001.zip](https://github.com/pxb1988/dex2jar/files/4578457/apk.zip.001.zip)
[apk.zip.002.zip](https://github.com/pxb1988/dex2jar/files/4578459/apk.zip.002.zip)
[apk.zip.003.zip](https://github.com/pxb1988/dex2jar/files/4578460/apk.zip.003.zip)

apk files split into several zip.
The app had split apk.
Is this the reason dex2jar failed?

**Comment by lihas** [comment]
> 
> 
> [ludo.apk-error.zip](https://github.com/pxb1988/dex2jar/files/4512167/ludo.apk-error.zip)

Did you find any solution?
Were you able to progress further?

**Comment by lihas** [comment]
https://github.com/pxb1988/dex2jar/issues/54
This issue seems related. Will try fix mentioned over there.

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
