### ISSUE TITLE
queries with dex2jar2.0

### ISSUE THREAD

**Issue by JaneEmi** [pxb1988/dex2jar#40]
Dear Mr.Bob Pan,
Greeting !!!
I would like to thank you for all for your previous version of dex2jar, especially 0.0.9.15. It has been very powerful supportive tool for me in decompiling . 
I am student research scholar , I have automated apk decompilation using java code. I wanted to upgrade my work with  dex2jar 2.0 to decompile recent apks . I wanted make use of d2j-asm-verify.sh and d2j-apk-sign.sh . But is not available. 

Can you please let me know if any other .sh file has these with functionalities integrated in dex2jar2.0???

Thanks for your time in advance.

**Comment by TamilanPeriyasamy** [comment]
Follow given steps:
  Replace the needed .sh files any other dex2jar tools folder 

OR

1.Get source 
       git clone -b 2.x https://github.com/pxb1988/dex2jar.git dex2jar-2.x
2.View the this path have d2j-asm-verify.sh and d2j-apk-sign.sh
       dex2jar-2.x/dex-tools/build/generated-sources/
3. Replace given files the your dex2jar tool folder.
