### ISSUE TITLE
Dex2jar for multidex.

### ISSUE THREAD

**Issue by JaneEmi** [pxb1988/dex2jar#41]
Hi!

I was trying to decompile multidex apk file with dex2jar 2.0 . The first dex class was decompiled but the later dex files did not get decompiled.
Supposing i have an apk with two dex file while extracting. Classes1.dex and classes2.dex.
Classes1.dex  is decompiled successfully. But applying same logic to classes2.dex decompilation is unsuccessful with the below error ;

Detail Error Information in File ./classes2-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible

Why does such a error come ? How can i come it ?

**Comment by TamilanPeriyasamy** [comment]
Only this error will be occur dex2jar-2.0 :
Recent Android vesion automatically applied multidex(multi classes ) Concept.
Classes.dex =>     classes.dex , classes2.dex.
