### ISSUE TITLE
Recompiling a apk

### ISSUE THREAD

**Issue by JaneEmi** [pxb1988/dex2jar#42]
For my research purpose i have decompiled a apk and converted it into jasmin file. 
While recompiling these jasmine files back to jar there occurs a 

/test_AudioDemoSec_jasmin/android/annotation/SuppressLint.j line 5:20 mismatched input 'Ljava/lang/annotation/Retention;' expecting set null
/test_AudioDemoSec_jasmin/android/annotation/SuppressLint.j line 6:49 mismatched input '"CLASS"' expecting set null
/test_AudioDemoSec_jasmin/android/annotation/SuppressLint.j line 8:20 mismatched input 'Ljava/lang/annotation/Target;' expecting set null
/test_AudioDemoSec_jasmin/android/annotation/SuppressLint.j line 9:46 required (...)+ loop did not match anything at input '"TYPE"'
STDERR  java.lang.NullPointerException
STDERR  java.lang.NullPointerException
STDERR      at com.googlecode.d2j.jasmin.JasminParser.unEscape(JasminParser.java:356)
STDERR      at com.googlecode.d2j.jasmin.JasminParser.sField(JasminParser.java:5672)
STDERR      at com.googlecode.d2j.jasmin.JasminParser.sFile(JasminParser.java:1062)
STDERR      at com.googlecode.d2j.jasmin.JasminParser.parse(JasminParser.java:961)
STDERR      at com.googlecode.d2j.jasmin.Jasmin2JarCmd.assemble1(Jasmin2JarCmd.java:130)
STDERR      at com.googlecode.d2j.jasmin.Jasmin2JarCmd.access$0(Jasmin2JarCmd.java:121)
STDERR      at com.googlecode.d2j.jasmin.Jasmin2JarCmd$1.visitFile(Jasmin2JarCmd.java:114)
STDERR      at com.googlecode.d2j.jasmin.Jasmin2JarCmd$1.visitFile(Jasmin2JarCmd.java:1)
STDERR      at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
STDERR      at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
STDERR      at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
STDERR      at java.nio.file.Files.walkFileTree(Files.java:2602)
STDERR      at java.nio.file.Files.walkFileTree(Files.java:2635)
STDERR      at com.googlecode.d2j.jasmin.Jasmin2JarCmd.travelFileTree(Jasmin2JarCmd.java:110)
STDERR      at com.googlecode.d2j.jasmin.Jasmin2JarCmd.assemble0(Jasmin2JarCmd.java:99)
STDERR      at com.googlecode.d2j.jasmin.Jasmin2JarCmd.doCommandLine(Jasmin2JarCmd.java:92)
STDERR      at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
STDERR      at com.googlecode.d2j.jasmin.Jasmin2JarCmd.main(Jasmin2JarCmd.java:56)

Can one please Help me resolve this issue  ?

Thanks in advance

**Comment by TamilanPeriyasamy** [comment]
Hi JaneEmi...
Please you download the old version for dex2jar 0.0.9.12 (dex2jar-0.0.9.12)
Jasmin to jar conversion Functionality fully worked.
Thank u.......!
