### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by JinghaoZhao** [pxb1988/dex2jar#433]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/5811722/classes-error.zip)

**Comment by MuratAKSARAY** [comment]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/5848436/classes-error.zip)

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
