### ISSUE TITLE
classes-error for WhatsApp 2.21.1.10

### ISSUE THREAD

**Issue by kurthuwig** [pxb1988/dex2jar#434]
https://apkpure.com/whatsapp-messenger/com.whatsapp/download?from=details

https://download.apkpure.com/b/APK/Y29tLndoYXRzYXBwXzIxMDExMDAwMF9mZGU0ZjdjOQ?_fn=V2hhdHNBcHAgTWVzc2VuZ2VyX3YyLjIxLjEuMTBfYXBrcHVyZS5jb20uYXBr&as=81d79a84423a3dcd7d2eb8aaff7747886005a65f&ai=54970612&at=1610982887&_sa=ai%2Cat&k=13377349921049687b32e0453d33a575600848e7&_p=Y29tLndoYXRzYXBw&c=1%7CCOMMUNICATION%7CZGV2PVdoYXRzQXBwJTIwSW5jLiZ0PWFwayZzPTQxNDcyNTE3JnZuPTIuMjEuMS4xMCZ2Yz0yMTAxMTAwMDA&hot=1

[classes-error.zip](https://github.com/pxb1988/dex2jar/files/5831023/classes-error.zip)

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
