### ISSUE TITLE
methods fail to translate

### ISSUE THREAD

**Issue by U2tzJTNE** [pxb1988/dex2jar#437]
version: [dex-reader-2.1-SNAPSHOT, dex-reader-api-2.1-SNAPSHOT, dex-ir-2.1-SNAPSHOT, d2j-smali-2.1-SNAPSHOT, d2j-base-cmd-2.1-SNAPSHOT, dex-tools-2.1-SNAPSHOT, dex-translator-2.1-SNAPSHOT]
cmdline: [.\news_article.apk]
env:
java.runtime.name: Java(TM) SE Runtime Environment
java.vm.version: 25.261-b12
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name: Java Virtual Machine Specification
java.runtime.version: 1.8.0_261-b12
java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs: C:\Program Files\Java\jdk1.8.0_261\jre\lib\endorsed
java.io.tmpdir: C:\Users\u2tzjtne\AppData\Local\Temp\
java.vm.specification.vendor: Oracle Corporation
java.library.path: C:\Program Files\Java\jdk1.8.0_261\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\NetSarang\Xftp 6\;C:\Program Files (x86)\NetSarang\Xshell 6\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Java\jdk1.8.0_261\bin;C:\Program Files\Java\jdk1.8.0_261\jre\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd
java.specification.name: Java Platform API Specification
java.class.version: 52.0
java.awt.printerjob: sun.awt.windows.WPrinterJob
java.specification.version: 1.8
java.class.path: C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\antlr-3.5.2.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\antlr-runtime-3.5.2.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\antlr4-4.5.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\antlr4-runtime-4.5.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\asm-debug-all-5.0.3.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\d2j-base-cmd-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\d2j-jasmin-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\d2j-smali-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\dex-ir-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\dex-reader-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\dex-reader-api-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\dex-tools-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\dex-translator-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\dex-writer-2.1-SNAPSHOT.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\dx-23.0.0.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\org.abego.treelayout.core-1.0.1.jar;C:\Users\u2tzjtne\Android\Decompile\Tools\dex2jar\lib\ST4-4.0.8.jar;
java.vm.specification.version: 1.8
java.home: C:\Program Files\Java\jdk1.8.0_261\jre
java.specification.vendor: Oracle Corporation
java.vm.info: mixed mode
java.version: 1.8.0_261
java.ext.dirs: C:\Program Files\Java\jdk1.8.0_261\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.vendor: Oracle Corporation
java.vendor.url.bug: http://bugreport.sun.com/bugreport/

================= 0 ===================
Lcom/ss/android/ad/brandlist/linechartview/b/d;.b(FFI)I
java.lang.RuntimeException: fail exe a40 = a28
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:92)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:255)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
	at com.googlecode.dex2jar.ir.ts.Ir2JRegAssignTransformer.transform(Ir2JRegAssignTransformer.java:182)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:167)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:442)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:40)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:132)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:575)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:434)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:450)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:175)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
Caused by: java.lang.NullPointerException
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:89)
	at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.onUseLocal(SimpleLiveAnalyze.java:27)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:166)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.onUse(BaseAnalyze.java:31)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:331)
	at com.googlecode.dex2jar.ir.ts.Cfg.travel(Cfg.java:387)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.exec(BaseAnalyze.java:90)
	... 17 more

.method public b(FFI)I
  .registers 16
    const/4 v0, 3
    new-array v0, v0, [Ljava/lang/Object;
    new-instance v1, Ljava/lang/Float;
    invoke-direct { v1, p1 }, Ljava/lang/Float;-><init>(F)V
    const/4 v2, 0
    aput-object v1, v0, v2
    new-instance v1, Ljava/lang/Float;
    invoke-direct { v1, p2 }, Ljava/lang/Float;-><init>(F)V
    const/4 v3, 1
    aput-object v1, v0, v3
    new-instance v1, Ljava/lang/Integer;
    invoke-direct { v1, p3 }, Ljava/lang/Integer;-><init>(I)V
    const/4 v4, 2
    aput-object v1, v0, v4
    sget-object v1, Lcom/ss/android/ad/brandlist/linechartview/b/d;->g:Lcom/meituan/robust/ChangeQuickRedirect;
    const v5, 105257
    invoke-static { v0, p0, v1, v2, v5 }, Lcom/meituan/robust/PatchProxy;->proxy([Ljava/lang/Object;Ljava/lang/Object;Lcom/meituan/robust/ChangeQuickRedirect;ZI)Lcom/meituan/robust/PatchProxyResult;
    move-result-object v0
    iget-boolean v1, v0, Lcom/meituan/robust/PatchProxyResult;->isSupported:Z
    if-eqz v1, :L0
    iget-object p1, v0, Lcom/meituan/robust/PatchProxyResult;->result:Ljava/lang/Object;
    check-cast p1, Ljava/lang/Integer;
    invoke-virtual { p1 }, Ljava/lang/Integer;->intValue()I
    move-result p1
    return p1
  :L0
    iget-object v0, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    const/4 v1, -1
    if-eqz v0, :L19
    invoke-interface { v0 }, Ljava/util/List;->isEmpty()Z
    move-result v0
    if-eqz v0, :L1
    goto/16 :L19
  :L1
    iget-object v0, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    invoke-interface { v0 }, Ljava/util/List;->size()I
    move-result v0
    sub-int/2addr v0, v3
  :L2
    if-ge v2, v0, :L8
    add-int v5, v2, v0
    div-int/2addr v5, v4
    iget-object v6, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    invoke-interface { v6, v5 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v6
    check-cast v6, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;
    invoke-virtual { v6 }, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;->getX()F
    move-result v6
    sub-float/2addr v6, p1
    iget-object v7, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    add-int/lit8 v8, v5, 1
    invoke-interface { v7, v8 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v7
    check-cast v7, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;
    invoke-virtual { v7 }, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;->getX()F
    move-result v7
    sub-float/2addr v7, p1
    invoke-static { v6 }, Ljava/lang/Math;->abs(F)F
    move-result v9
    invoke-static { v7 }, Ljava/lang/Math;->abs(F)F
    move-result v7
    cmpg-float v10, v7, v9
    if-gez v10, :L4
  :L3
    move v2, v8
    goto :L2
  :L4
    cmpg-float v7, v9, v7
    if-gez v7, :L5
    goto :L6
  :L5
    float-to-double v6, v6
    const-wide/16 v9, 0
    cmpl-double v11, v6, v9
    if-ltz v11, :L7
  :L6
    move v0, v5
    goto :L2
  :L7
    cmpg-double v5, v6, v9
    if-gez v5, :L2
    goto :L3
  :L8
    if-eq v0, v1, :L18
    iget-object v1, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    invoke-interface { v1, v0 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v1
    check-cast v1, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;
    invoke-virtual { v1 }, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;->getX()F
    move-result v1
    const/16 v2, 15
    if-ne p3, v2, :L9
    cmpg-float p1, v1, p1
    if-gez p1, :L10
    iget-object p1, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    invoke-interface { p1 }, Ljava/util/List;->size()I
    move-result p1
    sub-int/2addr p1, v3
    if-ge v0, p1, :L10
    add-int/lit8 v0, v0, 1
    goto :L10
  :L9
    const/16 v2, 16
    if-ne p3, v2, :L10
    cmpl-float p1, v1, p1
    if-lez p1, :L10
    if-lez v0, :L10
    add-int/lit8 v0, v0, -1
  :L10
    invoke-static { p2 }, Ljava/lang/Float;->isNaN(F)Z
    move-result p1
    if-nez p1, :L18
  :L11
    if-lez v0, :L12
    iget-object p1, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    add-int/lit8 p3, v0, -1
    invoke-interface { p1, p3 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object p1
    check-cast p1, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;
    invoke-virtual { p1 }, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;->getX()F
    move-result p1
    cmpl-float p1, p1, v1
    if-nez p1, :L12
    add-int/lit8 v0, v0, -1
    goto :L11
  :L12
    iget-object p1, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    invoke-interface { p1, v0 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object p1
    check-cast p1, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;
    invoke-virtual { p1 }, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;->getY()F
    move-result p1
  :L13
    move p3, v0
  :L14
    add-int/2addr v0, v3
    iget-object v2, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    invoke-interface { v2 }, Ljava/util/List;->size()I
    move-result v2
    if-lt v0, v2, :L15
    goto :L16
  :L15
    iget-object v2, p0, Lcom/ss/android/ad/brandlist/linechartview/b/d;->l:Ljava/util/List;
    invoke-interface { v2, v0 }, Ljava/util/List;->get(I)Ljava/lang/Object;
    move-result-object v2
    check-cast v2, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;
    invoke-virtual { v2 }, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;->getX()F
    move-result v4
    cmpl-float v4, v4, v1
    if-eqz v4, :L17
  :L16
    move v0, p3
    goto :L18
  :L17
    invoke-virtual { v2 }, Lcom/ss/android/ad/brandlist/linechartview/helper/Entry;->getY()F
    move-result v2
    sub-float/2addr v2, p2
    invoke-static { v2 }, Ljava/lang/Math;->abs(F)F
    move-result v2
    sub-float v4, p1, p2
    invoke-static { v4 }, Ljava/lang/Math;->abs(F)F
    move-result v4
    cmpg-float v2, v2, v4
    if-gtz v2, :L14
    move p1, p2
    goto :L13
  :L18
    return v0
  :L19
    return v1
.end method

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
