### ISSUE TITLE
New error report

### ISSUE THREAD

**Issue by Ob024** [pxb1988/dex2jar#438]
Trying to pull apart Space Shooter Galaxy Attack (one of the many versions, hard to even explain which one it is, I only know by picture lol) and ran into an error suggesting I upload this here to help, hope it helps! Thanks! :)

[classes-error.zip](https://github.com/pxb1988/dex2jar/files/5920747/classes-error.zip)

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
