### ISSUE TITLE
How to use d2j-dex-recompute-checksum.sh 

### ISSUE THREAD

**Issue by TamilanPeriyasamy** [pxb1988/dex2jar#44]
How to use d2j-dex-recompute-checksum.sh shell command

**Comment by pxb1988** [comment]
the tool d2j-dex-recompute-checksum.sh is designed to update the crc / sha1 checksum, and the filesize of the dex header.

the common scenarios to use the tool:
1. after editing a dex by hand (by a binary editing tool, like tool Okteta on linux), 
2. increase the size of dex to hiding something after the dex.
3. a memory dumped dex file, dexdump complains 'Bad checksum'

```
Usage: d2j-dex-recompute-checksum.sh [options] <input.dex>
options: 
  -o,--output output .dex file, default is [dex-name]-rechecksum.dex
  -f,--force force overwrite existing dex file by -o,--output
```

there are to way to invoke the command,
1. d2j-dex-recompute-checksum.sh
2. d2j_invoke.sh com.googlecode.dex2jar.tools.DexRecomputeChecksum

**Comment by TamilanPeriyasamy** [comment]
Okay very very thanks Bob Pan.
