### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by stdNullPtr** [pxb1988/dex2jar#446]
Hi, got an error while decompiling the Spark app.
I've attached the apk and the error info.

[Spark_base.zip](https://github.com/pxb1988/dex2jar/files/6074689/Spark_base.zip)

[Spark_base-error.zip](https://github.com/pxb1988/dex2jar/files/6074686/Spark_base-error.zip)

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
