### ISSUE TITLE
某个dex转jar报错了！

### ISSUE THREAD

**Issue by cjycjw** [pxb1988/dex2jar#449]
[classes2-error.zip](https://github.com/pxb1988/dex2jar/files/6162981/classes2-error.zip)

**Comment by geilige** [comment]
试试看 https://github.com/geilige/dex2jar/releases

**Comment by dicce3** [comment]
> 试试看 https://github.com/geilige/dex2jar/releases

大手，为什么在这里下载的不能用，在你这个链接里面的就能用，是不是升级了什么东西啊？

**Comment by geilige** [comment]
> > 试试看 https://github.com/geilige/dex2jar/releases
> 
> 大手，为什么在这里下载的不能用，在你这个链接里面的就能用，是不是升级了什么东西啊？

不敢当，升级的内容也是社区提交的，作者没合并，我给手动合并了，附加上了原提交人，可以看下我的提交记录哈

**Comment by dicce3** [comment]
> > > 试试看 https://github.com/geilige/dex2jar/releases
> > 
> > 
> > 大手，为什么在这里下载的不能用，在你这个链接里面的就能用，是不是升级了什么东西啊？
> 
> 不敢当，升级的内容也是社区提交的，作者没合并，我给手动合并了，附加上了原提交人，可以看下我的提交记录哈

### **那你也很牛拉，解决了我的问题，太扎实拉！！。******

**Comment by geilige** [comment]
> > > > 试试看 https://github.com/geilige/dex2jar/releases
> > > 
> > > 
> > > 大手，为什么在这里下载的不能用，在你这个链接里面的就能用，是不是升级了什么东西啊？
> > 
> > 
> > 不敢当，升级的内容也是社区提交的，作者没合并，我给手动合并了，附加上了原提交人，可以看下我的提交记录哈
> 
> ### **那你也很牛拉，解决了我的问题，太扎实拉！！。******

谢谢夸奖，能帮助到你我也很开心

**Comment by pxb1988** [comment]
主线版本已经不存在这个问题了，你可以试试。
the dex works on lastest release https://github.com/pxb1988/dex2jar/releases please have a try.
