### ISSUE TITLE
java.lang.IndexOutOfBoundsException: fromIndex < 0: -1

### ISSUE THREAD

**Issue by LukeKeywalker** [pxb1988/dex2jar#45]
Probably some kind of anti-dex2jar trick. Any idea how to bypass this?

[classes-error.zip](https://github.com/pxb1988/dex2jar/files/52601/classes-error.zip)

**Comment by pxb1988** [comment]
I believe the following two should solve this issue

https://github.com/pxb1988/dex2jar/commit/60599ef4e47dec64a4632e2eac2e822d47f2bc6b
fix crash on negative arraysize, https://bitbucket.org/pxb1988/dex2jar/issues/2/decompiler-error

https://github.com/pxb1988/dex2jar/commit/f8ad4dc98ece7128c7033c3d611713f6a6998aea
replace to 'throw new NegativeArraySizeException()' when init a nagative size array

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
