### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by arabesc** [pxb1988/dex2jar#450]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/6177450/classes-error.zip)
[classes2-error.zip](https://github.com/pxb1988/dex2jar/files/6177451/classes2-error.zip)
[classes3-error.zip](https://github.com/pxb1988/dex2jar/files/6177452/classes3-error.zip)

**Comment by geilige** [comment]
> [classes-error.zip](https://github.com/pxb1988/dex2jar/files/6177450/classes-error.zip)
> [classes2-error.zip](https://github.com/pxb1988/dex2jar/files/6177451/classes2-error.zip)
> [classes3-error.zip](https://github.com/pxb1988/dex2jar/files/6177452/classes3-error.zip)

试试看 https://github.com/geilige/dex2jar/releases

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
