### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by it-dainb** [pxb1988/dex2jar#451]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/6215707/classes-error.zip)

**Comment by geilige** [comment]
> [classes-error.zip](https://github.com/pxb1988/dex2jar/files/6215707/classes-error.zip)

试试看 https://github.com/geilige/dex2jar/releases

**Comment by pxb1988** [comment]
the dex works on latest release https://github.com/pxb1988/dex2jar/releases please have a try.
