### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by ZahraHussaini** [pxb1988/dex2jar#453]
Error-zip
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/6270698/classes-error.zip)

**Comment by geilige** [comment]
> Error-zip
> [classes-error.zip](https://github.com/pxb1988/dex2jar/files/6270698/classes-error.zip)

试试看 https://github.com/geilige/dex2jar/releases

**Comment by pxb1988** [comment]
the dex works on lastest release https://github.com/pxb1988/dex2jar/releases please have a try.
