### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by Stivino** [pxb1988/dex2jar#454]
[Ampler Bikes_v1.12.9-20200722-7a9233a_apkpure.com-error.zip](https://github.com/pxb1988/dex2jar/files/6292357/Ampler.Bikes_v1.12.9-20200722-7a9233a_apkpure.com-error.zip)

**Comment by pxb1988** [comment]
the dex works on lastest release https://github.com/pxb1988/dex2jar/releases please have a try.
