### ISSUE TITLE
dex2jar unable to convert apk to jar file

### ISSUE THREAD

**Issue by navneet8603** [pxb1988/dex2jar#456]
[esaral.zip-error.zip](https://github.com/pxb1988/dex2jar/files/6327540/esaral.zip-error.zip)
The source code of the apk file i am trying to get is [here](http://dl.apk-cloud.com/dl5/apk/2021/3/3/com.spayee.esaral.reader_299.apk?id=com.spayee.esaral.reader&f=eSaral%20-%20JEE%2C%20NEET%2C%20Class%209%20%2010%20Preparation%20App_2.8.2_apk-dl.com.apk&dl=2)
Please help me fix the error.
I will be thankful for help!

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
