### ISSUE TITLE
Errors Translating: Landroid/widget/RemoteViews$ReflectionAction; Landroid/widget/RemoteViews$ViewContentNavigation;

### ISSUE THREAD

**Issue by kevinhbiomerieux** [pxb1988/dex2jar#459]
From SDK 29
[summary.txt](https://github.com/pxb1988/dex2jar/files/6361353/summary.txt)

**Comment by pxb1988** [comment]
the ClassCastException should been fixed in https://github.com/pxb1988/dex2jar/commit/b004967677a6667ad5b06af3b04612c628276c29

please try the latest version of dex2jar
