### ISSUE TITLE
Detail Error Information

### ISSUE THREAD

**Issue by Hyffer** [pxb1988/dex2jar#466]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/6447709/classes-error.zip)
[classes2-error.zip](https://github.com/pxb1988/dex2jar/files/6447710/classes2-error.zip)

huge thanks to your hard work!

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
