### ISSUE TITLE
java.lang.RuntimeException: can not merge I and Z

### ISSUE THREAD

**Issue by rudra-pilankar** [pxb1988/dex2jar#471]
[base-error.zip](https://github.com/pxb1988/dex2jar/files/6564048/base-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
