### ISSUE TITLE
Detail Error Information in File

### ISSUE THREAD

**Issue by MageshSundarG** [pxb1988/dex2jar#472]
[Scandit_Demo_base-error.zip](https://github.com/pxb1988/dex2jar/files/6628418/Scandit_Demo_base-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
