### ISSUE TITLE
Decompile Error

### ISSUE THREAD

**Issue by gogolch** [pxb1988/dex2jar#473]
[
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/6643501/classes-error.zip)
]

here the error that i received when use dex2jar.

Regards

**Comment by ThexXTURBOXx** [comment]
This issue is most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
