### ISSUE TITLE
Decompiling error

### ISSUE THREAD

**Issue by mttbyte** [pxb1988/dex2jar#475]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/6686411/classes-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
