### ISSUE TITLE
Dex2jar as project

### ISSUE THREAD

**Issue by JaneEmi** [pxb1988/dex2jar#48]
Hi there!

I am looking for assistance to download the dex2jar as project. I tried downloading the zip but  when imported to work space error are generated stating missing packages. 

Please suggest me some possible solution.

Thank you

**Comment by TamilanPeriyasamy** [comment]
1.Download and install Intellij IDEA .
2. Get the code for by Git
    1.get source 
           git clone -b 2.x https://github.com/pxb1988/dex2jar.git dex2jar-2.x
     2. build the project via gradle
          cd dex2jar-2.x
          gradle clean distZip

Refer this link:
Please refer https://github.com/pxb1988/dex2jar/wiki/BuildFromSource for building instruction.

**Comment by JaneEmi** [comment]
Very useful..! 
Thank you for sharing your knowledge
