### ISSUE TITLE
CPU utilization is too high

### ISSUE THREAD

**Issue by zhoukangg** [pxb1988/dex2jar#480]
There is a problem that has been bothering me.

I am using the function of dex2jar,  the version is 2.0 .
sh ./dex2jar/d2j-dex2jar.sh ./classes.dex --force -o ./someAPK.jar

It is often the cup occupancy rate reaches 98 or even higher. Is it normal, or how can I fix it?

**Comment by zhoukangg** [comment]
cpu is 8 core, memory is 32g

**Comment by pxb1988** [comment]
could please attach the dex file, so I can reproduce the issue.
