### ISSUE TITLE
dex file parsing problem

### ISSUE THREAD

**Issue by thesourcerer8** [pxb1988/dex2jar#482]
[classes2.zip](https://github.com/pxb1988/dex2jar/files/6877639/classes2.zip)
I got the error message: classes2.dex: Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.

**Comment by izakdvlpr** [comment]
@thesourcerer8, same problem here :/

**Comment by ThexXTURBOXx** [comment]
This issue is most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Comment by pxb1988** [comment]
this dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
