### ISSUE TITLE
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.

### ISSUE THREAD

**Issue by s-pavanreddy** [pxb1988/dex2jar#483]
[dice-roller-different-error.zip](https://github.com/pxb1988/dex2jar/files/6887134/dice-roller-different-error.zip)
[dice-roller-different.zip](https://github.com/pxb1988/dex2jar/files/6887145/dice-roller-different.zip)
dice-roller-different.zip is apk renamed to zip because doesn't accept apk files here. Github makes life difficult :(

**Comment by ThexXTURBOXx** [comment]
This issue is most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
