### ISSUE TITLE
exception : java.lang.ArrayIndexOutOfBoundsException: 4

### ISSUE THREAD

**Issue by Freakboy** [pxb1988/dex2jar#485]
Instagram_v198_v7a\ProjectSrc\classes.dex -> .\classes-dex2jar.jar
>. Error process class: [7133]LX/22C;
>.. while accept method:[LX/22C;.A0K(LX/1tp;LX/2LG;Ljava/lang/String;I)V]
>... while accept parameter annotation in method:LX/22C;.A0K(LX/1tp;LX/2LG;Ljava/lang/String;I)V.
>.... while accept parameter annotation in parameter:[4]
>..... ROOT cause:
>java.lang.ArrayIndexOutOfBoundsException: 4
>	at com.googlecode.d2j.node.DexMethodNode$1.visitAnnotation(DexMethodNode.java:111)
>	at com.googlecode.d2j.node.DexAnnotationNode.accept(DexAnnotationNode.java:124)
>	at com.googlecode.d2j.reader.DexFileReader.read_annotation_item(DexFileReader.java:810)
>	at com.googlecode.d2j.reader.DexFileReader.read_annotation_set_item(DexFileReader.java:800)
>	at com.googlecode.d2j.reader.DexFileReader.read_annotation_set_ref_list(DexFileReader.java:1001)
>	at com.googlecode.d2j.reader.DexFileReader.acceptMethod(DexFileReader.java:955)
>	at com.googlecode.d2j.reader.DexFileReader.acceptClass(DexFileReader.java:764)
>	at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:600)
>	at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:565)
>	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:85)
>	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:272)
>	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:108)
>	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
>	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
>Detail Error Information in File .\classes-error.zip
>Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.

**Comment by ThexXTURBOXx** [comment]
This issue is now most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar
Please note, however, that there is still one `Exception` thrown because of some method being too long for ASM.

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**
