### ISSUE TITLE
Please report this file to one of following link if possible

### ISSUE THREAD

**Issue by miqinouba** [pxb1988/dex2jar#487]
dex2jar classes.dex -> .\classes-dex2jar.jar
Detail Error Information in File .\classes-error.zip
Please report this file to one of following link if possible (any one).

version: dex2jar-2.1

[classes-error.zip](https://github.com/pxb1988/dex2jar/files/6987654/classes-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is maybe fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
