### ISSUE TITLE
Methods failed to translate

### ISSUE THREAD

**Issue by roxasthenobody98** [pxb1988/dex2jar#489]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/7011288/classes-error.zip)

9 methods failed to translate. 

dex2jar 2.0
Windows 10 21H1 Build 19043
WSL  - Ubuntu 20.04 LTS
OpenJDK 16 openjdk-16-jre-headless

**Comment by ThexXTURBOXx** [comment]
This issue is now most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
