### ISSUE TITLE
Windows 10 - Lords Mobile 2.55 - Error executing dex2jar

### ISSUE THREAD

**Issue by pyorokun7** [pxb1988/dex2jar#490]
dex2jar ..\lordsmobile_2.55.apk -> .\lordsmobile_2.55-dex2jar.jar

Microsoft Windows [Version 10.0.19042.1165]
>java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

[lordsmobile_2.55-error.zip](https://github.com/pxb1988/dex2jar/files/7018662/lordsmobile_2.55-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is now most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
