### ISSUE TITLE
dex2jar failed on GBoard

### ISSUE THREAD

**Issue by Craftist** [pxb1988/dex2jar#492]
[gboard-error.zip](https://github.com/pxb1988/dex2jar/files/7032922/gboard-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is now most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
this issue is fixed on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
