### ISSUE TITLE
Error decompiling

### ISSUE THREAD

**Issue by Sternbach-Software** [pxb1988/dex2jar#493]
Here are the error and apk files. It said it couldn't decompile. I was using the command line on Windows.
[Dolphin Emulator_v5.0-14344_apkpure.com-error.zip](https://github.com/pxb1988/dex2jar/files/7042703/Dolphin.Emulator_v5.0-14344_apkpure.com-error.zip)
[Dolphin Emulator_v5.0-14344_apkpure.com.zip](https://github.com/pxb1988/dex2jar/files/7042706/Dolphin.Emulator_v5.0-14344_apkpure.com.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is most likely fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
