### ISSUE TITLE
Error decompiling Minecraft

### ISSUE THREAD

**Issue by lispy2010** [pxb1988/dex2jar#494]
I am trying to decompile Minecraft Bedrock Edition, but it gives me an error.
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/7046418/classes-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
