### ISSUE TITLE
Error decompiling classes.dex file

### ISSUE THREAD

**Issue by MumiaIrrequieta** [pxb1988/dex2jar#495]
Hi,

I got an error message to report this error file [classes-error.zip](https://github.com/pxb1988/dex2jar/files/7077083/classes-error.zip) when trying to decompile this file [classes.dex.zip](https://github.com/pxb1988/dex2jar/files/7077070/classes.dex.zip).
I'm using the latest 2.1-20171001-lanchon version.
Can someone please help?
Thanks in advance.

**Comment by ThexXTURBOXx** [comment]
This issue is fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
