### ISSUE TITLE
apk to jar file converting error

### ISSUE THREAD

**Issue by ghost** [pxb1988/dex2jar#496]
[Starmaker-error.zip](https://github.com/pxb1988/dex2jar/files/7120200/Starmaker-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
