### ISSUE TITLE
d2j-dex2jar classes.dex  error

### ISSUE THREAD

**Issue by bokuang** [pxb1988/dex2jar#498]
Detail Error Information in File .\classes-error.zip

[classes-error.zip](https://github.com/pxb1988/dex2jar/files/7161355/classes-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
