### ISSUE TITLE
Error when recompilling with jar2dex.

### ISSUE THREAD

**Issue by ghost** [pxb1988/dex2jar#499]
PS C:\Users\Maintenance\VM\super_image_tools_v15\priv-app\MiuiMusicGlobal> jar2dex .\MiuiMusicGlobal-dex2jar-Patched.jar --force
jar2dex .\MiuiMusicGlobal-dex2jar-Patched.jar -> MiuiMusicGlobal-dex2jar-Patched-jar2dex.dex
call com.android.dx.command.Main.main[--dex, --no-strict, --output=C:\Users\Maintenance\VM\super_image_tools_v15\priv-app\MiuiMusicGlobal\MiuiMusicGlobal-dex2jar-Patched-jar2dex.dex, C:\Users\Maintenance\VM\super_image_tools_v15\priv-app\MiuiMusicGlobal\.\MiuiMusicGlobal-dex2jar-Patched.jar]

trouble writing output: Too many method references: 157375; max is 65536.
You may try using --multi-dex option.
References by package:

**Comment by ThexXTURBOXx** [comment]
``You may try using --multi-dex option.``

**Comment by ghost** [comment]
> `You may try using --multi-dex option.`

I forgot to say that i already tried this option. ^^

**Comment by ThexXTURBOXx** [comment]
In that case, try my fork. But I can't promise much as I didn't fix many things for jar2dex. I focused more on dex2jar

My fork can be found here; https://github.com/ThexXTURBOXx/dex2jar
Downloads can be found in the releases.

**Comment by pxb1988** [comment]
there are too many classes in you jar, can't direct convert to a single dex.

please call the `dx` in android sdk directly 

````
dx --dex --no-strict --multi-dex --output=C:\Users\Maintenance\VM\super_image_tools_v15\priv-app\MiuiMusicGlobal\MiuiMusicGlobal-dex2jar-Patched-jar2dex.jar C:\Users\Maintenance\VM\super_image_tools_v15\priv-app\MiuiMusicGlobal.\MiuiMusicGlobal-dex2jar-Patched.jar
````
