### ISSUE TITLE
Not working says please report issue here

### ISSUE THREAD

**Issue by namanop** [pxb1988/dex2jar#503]
[classes-error.zip](https://github.com/pxb1988/dex2jar/files/7229469/classes-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
https://github.com/pxb1988/dex2jar/releases/tag/v2.1 works on the zip, please have a try.
