### ISSUE TITLE
Reported file

### ISSUE THREAD

**Issue by jorgebenzeno** [pxb1988/dex2jar#504]
[ST25NFCTap-signed-V3.7.0-error.zip](https://github.com/pxb1988/dex2jar/files/7230500/ST25NFCTap-signed-V3.7.0-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by jorgebenzeno** [comment]
thanks

**Comment by pxb1988** [comment]
https://github.com/pxb1988/dex2jar/releases/tag/v2.1 works on the zip, please have a try.
