### ISSUE TITLE
JYouPro fitness band app

### ISSUE THREAD

**Issue by fudge-1** [pxb1988/dex2jar#505]
[JYouPro-error.zip](https://github.com/pxb1988/dex2jar/files/7262202/JYouPro-error.zip)

Thanks!

**Comment by ThexXTURBOXx** [comment]
This issue is fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
https://github.com/pxb1988/dex2jar/releases/tag/v2.1 works on the zip, please have a try.
