### ISSUE TITLE
Crash On Songtube App & Its Free And opensource im just test it to see how this tool works.

### ISSUE THREAD

**Issue by Fire7ly** [pxb1988/dex2jar#506]
[sng-error.zip](https://github.com/pxb1988/dex2jar/files/7273055/sng-error.zip)

**Comment by ThexXTURBOXx** [comment]
This issue is fixed on my branch: https://github.com/ThexXTURBOXx/dex2jar

**Download available [here](https://github.com/ThexXTURBOXx/dex2jar/releases)**

**Comment by pxb1988** [comment]
https://github.com/pxb1988/dex2jar/releases/tag/v2.1 works on the zip, please have a try.

**Comment by Fire7ly** [comment]
> https://github.com/pxb1988/dex2jar/releases/tag/v2.1 works on the zip, please have a try.

Thanks A lot i will GIve it a Try Thanks
