### ISSUE TITLE
It was decompiled successfully. may be or may be not. but it gives this error.

### ISSUE THREAD

**Issue by workforanil** [pxb1988/dex2jar#508]
[WhatsApp-error.zip](https://github.com/pxb1988/dex2jar/files/7394696/WhatsApp-error.zip)

**Comment by pxb1988** [comment]
https://github.com/pxb1988/dex2jar/releases/tag/v2.1 can generate out jar.
but as some class have name like `LX/0Ef;`, the jar may reject by jvm
