### ISSUE TITLE
file with errors

### ISSUE THREAD

**Issue by JC3** [pxb1988/dex2jar#511]
```
C:\Programs\dex2jar-2.0>d2j-dex2jar.bat -f -o nix.jar classes.dex -> nix.jar
Detail Error Information in File .\classes-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.
```

Input file (compressed) and error log:
- [classes-error.zip](https://github.com/pxb1988/dex2jar/files/7406007/classes-error.zip)
- [classes.dex.gz](https://github.com/pxb1988/dex2jar/files/7406012/classes.dex.gz)

Dex2jar version is the one at https://github.com/pxb1988/dex2jar/releases/tag/2.0

OS is Windows 10, 64-bit.

**Comment by pxb1988** [comment]
the dex works on https://github.com/pxb1988/dex2jar/releases/tag/v2.1 please have a try.
