### ISSUE TITLE
Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap

### ISSUE THREAD

**Issue by nikan0ru** [pxb1988/dex2jar#515]
Everytime i try to convert a classes.dex file to jar it says this on cmd prompt

**Comment by P-Leo10** [comment]
I have the same problem. Did you manage to solve?

**Comment by ghost** [comment]
> Everytime i try to convert a classes.dex file to jar it says this on cmd prompt

Go To 
Control Panel>Systerm and secutiy>system>Advanced system settings(tab)>Environment Variables>System Variables>New

**Variable name**: `_JAVA_OPTIONS`
**Variable value**: `-Xmx512M`

Now restart the Command Prompt and try again

**Comment by nikan0ru** [comment]
Thanks that was the solution i was looking for

**Comment by nikan0ru** [comment]
> I have the same problem. Did you manage to solve?

refer to @SirLez's comment

**Comment by founanic** [comment]
> > Everytime i try to convert a classes.dex file to jar it says this on cmd prompt
> 
> Go To Control Panel>Systerm and secutiy>system>Advanced system settings(tab)>Environment Variables>System Variables>New
> 
> **Variable name**: `_JAVA_OPTIONS` **Variable value**: `-Xmx512M`
> 
> Now restart the Command Prompt and try again

its works (y)

**Comment by headfirst123** [comment]
你的来信已收到，谢谢
