### ISSUE TITLE
classes-error

### ISSUE THREAD

**Issue by ajoudeh-personal** [pxb1988/dex2jar#540]
[classes-error-2.zip](https://github.com/pxb1988/dex2jar/files/8694602/classes-error-2.zip)

**Comment by ThexXTURBOXx** [comment]
You are still using dex2jar 2.0 which is very outdated.
Try using 2.1 or my fork: https://github.com/ThexXTURBOXx/dex2jar

**Comment by ajoudeh-personal** [comment]
Ok Thanks
