### ISSUE TITLE
There are 86 methods fail to translate.

### ISSUE THREAD

**Issue by s4msecurity** [pxb1988/dex2jar#543]
[apk-error.zip](https://github.com/pxb1988/dex2jar/files/8836287/apk-error.zip)

**Comment by ThexXTURBOXx** [comment]
You are still using dex2jar 2.0 which is very outdated.
Either update to 2.1 or use my fork: https://github.com/ThexXTURBOXx/dex2jar

**Comment by s4msecurity** [comment]
Thanks! Issue fixed. I did make it with 2.1.

**Comment by ThexXTURBOXx** [comment]
Nice to hear, no problem!
Could you maybe close this issue then to keep things in order here? :)

**Comment by s4msecurity** [comment]
Yes, of course.
