### ISSUE TITLE
Could not find property 'arguments' on task ':d2j-smali:generateGrammarSource'

### ISSUE THREAD

**Issue by xete** [pxb1988/dex2jar#60]
I just try ./gradlew and gradle all, and the following is what it(gradle 2.2) outputs:

> - Where:<br>
>   Build file '/path/to/dex2jar/d2j-smali/build.gradle' line: 13<br>
> - What went wrong:<br>
>   A problem occurred evaluating project ':d2j-smali'.<br>
>   Could not find property 'arguments' on task ':d2j-smali:generateGrammarSource'.

Could anyone figure out how to fix it?

**Comment by CSGLabs** [comment]
i had a similar problem but i managed to build it with maven instead:
for ubuntu, try this:
sudo apt-get install maven
mvn clean package

[INFO] dex2jar ........................................... SUCCESS [3.464s]
[INFO] Dex Reader API .................................... SUCCESS [15.492s]
[INFO] Dex Reader ........................................ SUCCESS [2.103s]
[INFO] dex-writer ........................................ SUCCESS [2.730s]
[INFO] Dex Instruction Representation .................... SUCCESS [1.909s]
[INFO] d2j-base-cmd ...................................... SUCCESS [0.209s]
[INFO] d2j-smali ......................................... SUCCESS [18.229s]
[INFO] Dex Translator .................................... SUCCESS [17.322s]
[INFO] d2j-jasmin ........................................ SUCCESS [4.494s]
[INFO] Dex Tools ......................................... SUCCESS [6.792s]

source: https://sourceforge.net/p/dex2jar/wiki/BuildFromSource/

**Comment by pxb1988** [comment]
@xete Please update the gradle. I have tested gradle 2.8 which works fine

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 2.8
------------------------------------------------------------

Build time:   2015-10-20 03:46:36 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_95 (Oracle Corporation 24.95-b01)
OS:           Linux 4.4.1-2-ARCH amd64
```

**Comment by CSGLabs** [comment]
confirmed, thanks pxb, distro repos are running way behind.
