### ISSUE TITLE
Jar to classes.dex converion issue

### ISSUE THREAD

**Issue by TamilanPeriyasamy** [pxb1988/dex2jar#61]
Most of the apks have same issue.
How solve this one...
STDERR  
STDERR  EXCEPTION FROM SIMULATION:
STDERR  expected type byte[] but found java.lang.String[]
STDERR  
STDERR  ...at bytecode offset 0000007a
STDERR  locals[0000]: Lcom/a/a/a/m/f;
STDERR  locals[0001]: I
STDERR  locals[0002]: [Ljava/lang/String;
STDERR  locals[0003]: <invalid>
STDERR  locals[0004]: <invalid>
STDERR  locals[0005]: I
STDERR  ...while working on block 007a
STDERR  ...while working on method b:(Lcom/a/a/a/m/f;)Ljava/lang/Object;
STDERR  ...while processing b (Lcom/a/a/a/m/f;)Ljava/lang/Object;
STDERR  ...while processing com/a/a/a/h/g.class
STDERR  
STDERR  1 error; aborting

**Comment by pxb1988** [comment]
Seams its a type detection issue of dex2jar. 
Could you please provider an apk/dex to reproduce the issue ?
