### ISSUE TITLE
error on decompiling 

### ISSUE THREAD

**Issue by UchqunovS** [pxb1988/dex2jar#610]
[base-error.zip](https://github.com/pxb1988/dex2jar/files/13074499/base-error.zip)
What is this, on the decompile terminal I got "
Picked up _JAVA_OPTIONS: 
dex2jar base.apk -> ./base-dex2jar.jar
Detail Error Information in File ./base-error.zip
Please report this file to one of following link if possible (any one).
    https://sourceforge.net/p/dex2jar/tickets/
    https://bitbucket.org/pxb1988/dex2jar/issues
    https://github.com/pxb1988/dex2jar/issues
    dex2jar@googlegroups.com "

**Comment by ThexXTURBOXx** [comment]
Please try with the newest version first and follow the steps in https://github.com/pxb1988/dex2jar/issues/590
