### ISSUE TITLE
Detail Error Information in File .\00O000ll111l_0-error.zip

### ISSUE THREAD

**Issue by FAUST-BENCHOU** [pxb1988/dex2jar#611]
[00O000ll111l_0-error.zip](https://github.com/pxb1988/dex2jar/files/13294948/00O000ll111l_0-error.zip)
Detail Error Information in File .\00O000ll111l_0-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.

**Comment by ThexXTURBOXx** [comment]
Your version is way outdated. Please follow the steps in #590
