### ISSUE TITLE
Method too large during exception

### ISSUE THREAD

**Issue by gmorgachev** [pxb1988/dex2jar#613]
Example for method too large exception
Quite usual for asm's ClassWriter but might be useful

[summary.txt](https://github.com/pxb1988/dex2jar/files/14048903/summary.txt)
[classes.dex.zip](https://github.com/pxb1988/dex2jar/files/14048922/classes.dex.zip)

**Comment by ThexXTURBOXx** [comment]
There exists a workaround for this bug in my fork #486
