### ISSUE TITLE
So... this thing doesn't work on Windows at all?

### ISSUE THREAD

**Issue by MrAroGH** [pxb1988/dex2jar#616]
I have downloaded dex-tools v2.4 zip file, unpacked dex2jar, put my apk file in this folder and tried to run d2j-dex2jar.bat from separate CMD with following commands:
cd C:\Users\Admin\Desktop\dex2jar
d2j-dex2jar.bat unpack.apk
But this doesn't work and throws me an error saying "Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap"

**Comment by ThexXTURBOXx** [comment]
Either your computer does not have enough RAM for the predefined JVM parameters or the predefined JVM parameters are not enough for your apk/dex file. You need to adjust the `-Xmx` parameter inside the `d2j-invoke.bat` file.
However, please note that having <= 2GB RAM available is very close to the limit of dex2jar's usual needs. Sometimes it even needs 8GB RAM on my machine

**Comment by Entretoize** [comment]
I have 32GB of RAM and have the same error !

**Comment by ThexXTURBOXx** [comment]
@Entretoize Please follow what I suggested in [the comment above](https://github.com/pxb1988/dex2jar/issues/616#issuecomment-2067812151)

**Comment by Entretoize** [comment]
That's not clear, the parameter is -Xmx2048m and you say dex2jar needs at least 2GB, so should I increase the number ?

**Comment by ThexXTURBOXx** [comment]
> <= 2GB RAM available is very close to the limit of dex2jar's **usual** needs

I think, the **usual** should be pretty clear. On a 32 GB machine, try setting it to `-Xmx16G` for example. That should be plenty enough. And if it is still not enough, try increasing it even more. But if it still does not work at around `24G`, you might be out of luck for your use case
