### ISSUE TITLE
Issue with Symbol Renaming in dex2jar

### ISSUE THREAD

**Issue by shuytp** [pxb1988/dex2jar#630]
When using dex2jar to convert DEX files, I noticed that certain method names are automatically renamed. For example, the original method call:

```java
com.cn(-$.Lambda.BaseApplication);
```
is changed to:
```java
com.cn(_$.Lambda.BaseApplication);
```
I would like to know if there are configuration options to disable this automatic renaming, or if not, whether there are plans to add such a feature in the future.
Thank you!

**Comment by ThexXTURBOXx** [comment]
This is done intentionally in order to allow code to be decompiled directly to valid Java code.
But indeed, my fork has an option to turn it off: https://github.com/ThexXTURBOXx/dex2jar/blob/main/dex-tools/src/main/java/com/googlecode/dex2jar/tools/Dex2jarCmd.java#L61-L62
