### ISSUE TITLE
Problem in converting .dex file to .jar 

### ISSUE THREAD

**Issue by daylight-hole** [pxb1988/dex2jar#633]
[this](error keeps showing when i try to use dex2jar on a dex file. Is there a solution?  

"dex2jar classes.dex -> .\classes-dex2jar.jar
Detail Error Information in File .\classes-error.zip"

[classes-error.zip](https://github.com/user-attachments/files/17775187/classes-error.zip)

**Comment by ThexXTURBOXx** [comment]
Your version of dex2jar is way outdated. Could you please either try [the latest upstream release](https://github.com/pxb1988/dex2jar/releases/latest) or [the latest release of my fork](https://github.com/ThexXTURBOXx/dex2jar/releases/latest)?
