### ISSUE TITLE
Error while creating jar file from dex

### ISSUE THREAD

**Issue by coletz** [pxb1988/dex2jar#8]
OS: Windows 8.1 x86_64
SCRIPT: d2j-dex2jar.bat
PROBLEM:
when trying to create jar file from a dex one, using "d2j-dex2jar.bat classes.dex" I get the error reported in the file (created from the script) that you can find here 
http://www29.zippyshare.com/v/t3K00S8N/file.html

The file i've tried to decompile is there:
http://www29.zippyshare.com/v/wBaOOA63/file.html

**Comment by pxb1988** [comment]
similar with #3 
Please get the night build here http://repository-dex2jar.forge.cloudbees.com/snapshot/com/googlecode/d2j/dex-tools/2.1-SNAPSHOT/ and try again.

**Comment by coletz** [comment]
Sorry for the duplicate. Working with the 2.1, thanks
